source 'https://github.com/hufsm/mobile-ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

target 'SecureAccessBLE_Tests' do

  pod 'SwiftFormat/CLI'
  pod 'SwiftLint', '0.23.0'

  pod 'SecureAccessBLE', :path => '../'

  pod 'CommonUtils'#, '0.1.1'
  
end

target 'SecureAccessBLE' do
    pod 'CommonUtils'#, '0.1.1'
    pod 'CryptoSwift', '0.7.0'
end
