author: 'Huf Secure Mobile GmbH' 
github_url: "https://github.com/huf-development-services/mobile-ios-secure-access-ble" 
xcodebuild_arguments: [build,-workspace,Example/SecureAccessBLE.xcworkspace,-scheme,SecureAccessBLE-framework] 
module: 'SecureAccessBLE'
output: 'Docs'
min_acl: 'internal' # Could also be 'private'
