author: 'Huf Secure Mobile GmbH' 
github_url: "https://github.com/hufsm/mobile-ios-ble" 
xcodebuild_arguments: [build,-workspace,TACS.xcworkspace,-scheme,TACS] 
module: 'TACS'
output: 'Docs'
min_acl: 'internal' # Could also be 'private'