source 'https://github.com/hufsm/mobile-ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.3'
use_frameworks!

target 'TACS' do
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint', '0.28.0'
  pod 'SecureAccessBLE', :path => '../'

  target 'TACSTests' do
#    inherit! :search_paths
    pod 'Nimble', '8.0.1'
    pod 'Quick', '2.0.0'
  end

end

target 'SampleApp' do
  pod 'SecureAccessBLE', :path => '../'
end
