source 'https://github.com/hufsm/mobile-ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.3'

target 'TACS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  pod 'SecureAccessBLE', :path => '../'

  target 'TACSTests' do
#    inherit! :search_paths
    pod 'Nimble', '8.0.1'
    pod 'Quick', '2.0.0'
  end

end
